channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
      - 6
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
      - 6
  -
    id: diagnostics
    grants:
      - 3
      - 6
  -
    id: purger_varnish_fea27e4289
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_varnish_8c5c4fd6e0
    grants:
      - 0
      - 2
      - 3
