activate: false
auth_source: default-sp
login_link_display_name: 'Login with PIV or other Smartcard.'
login_link_show: true
user_name: adUPN
unique_id: VAUID
mail_attr: adUPN
header_no_cache: true
role:
  population: ''
  eval_every_time: false
register_users: false
allow:
  set_drupal_pwd: true
  default_login: true
  default_login_roles:
    authenticated: authenticated
    content_api_consumer: content_api_consumer
    documentation_editor: documentation_editor
    content_editor: content_editor
    content_reviewer: content_reviewer
    content_publisher: content_publisher
    content_admin: content_admin
    redirect_administrator: redirect_administrator
    admnistrator_users: admnistrator_users
    administrator: administrator
  default_login_users: '1,16'
logout_goto_url: ''
sync:
  mail: true
  user_name: true
autoenablesaml: true
debug: true
secure: true
httponly: false
