name: phpcs
on: [pull_request]
jobs:
  phpcs:
    name: runner / phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: acrollet/action-phpcs-drupal@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          phpcs_args: 'docroot/modules/custom docroot/themes/custom tests'
          phpcs_extensions: 'php,module,inc,install,profile,engine,theme,css'
          phpcs_ignore: '*.md,*.min.css,styles.css,wysiwyg.css,proofing.css,user_guides.css,*/node_modules/*,*/simplesaml*/*'

